import { deflateRawSync } from "node:zlib";
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import type { PrismaClient } from "@pitchmyweb/db";
import { prisma } from "../../../../../lib/db/client";
import { requireCurrentUser } from "../../../../../lib/auth/current-user";
import { errorResponse } from "../../../../../lib/api/response";
import { getWebsiteProjectForUser } from "../../../../../lib/websites/website.service";
import { cuidSchema } from "../../../../../lib/validation/common";

function crc32(data: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of data) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(value: number): Buffer {
  const buffer = Buffer.alloc(2);
  buffer.writeUInt16LE(value, 0);
  return buffer;
}

function u32(value: number): Buffer {
  const buffer = Buffer.alloc(4);
  buffer.writeUInt32LE(value >>> 0, 0);
  return buffer;
}

function createZip(files: Array<{ name: string; content: string }>): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;

  for (const file of files) {
    const name = Buffer.from(file.name, "utf8");
    const source = Buffer.from(file.content, "utf8");
    const compressed = deflateRawSync(source);
    const checksum = crc32(source);
    const local = Buffer.concat([Buffer.from("PK\x03\x04", "binary"), u16(20), u16(0), u16(8), u16(0), u16(0), u32(checksum), u32(compressed.length), u32(source.length), u16(name.length), u16(0), name, compressed]);
    localParts.push(local);

    centralParts.push(Buffer.concat([Buffer.from("PK\x01\x02", "binary"), u16(20), u16(20), u16(0), u16(8), u16(0), u16(0), u32(checksum), u32(compressed.length), u32(source.length), u16(name.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), name]));
    offset += local.length;
  }

  const central = Buffer.concat(centralParts);
  const local = Buffer.concat(localParts);
  const end = Buffer.concat([Buffer.from("PK\x05\x06", "binary"), u16(0), u16(0), u16(files.length), u16(files.length), u32(central.length), u32(local.length), u16(0)]);
  return Buffer.concat([local, central, end]);
}

export async function handleDownloadWebsite(db: PrismaClient, request: NextRequest, projectId: string): Promise<NextResponse> {
  const user = await requireCurrentUser(db, request);
  const project = await getWebsiteProjectForUser(db, user.id, cuidSchema.parse(projectId));
  const zip = createZip([
    { name: "README.md", content: `# ${project.template} site\n\nGenerated by PitchMyWeb. The source data is in site-data/content.json and site-data/design.json.\n` },
    { name: "site-data/content.json", content: JSON.stringify(project.contentJSON, null, 2) },
    { name: "site-data/design.json", content: JSON.stringify(project.designJSON ?? {}, null, 2) },
    { name: "site-data/manifest.json", content: JSON.stringify({ template: project.template, theme: project.theme, slug: project.slug, versionCount: project.versions.length }, null, 2) },
  ]);

  return new NextResponse(new Uint8Array(zip), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="pitchmyweb-${project.slug}.zip"`,
      "Content-Length": String(zip.length),
    },
  });
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }): Promise<NextResponse> {
  try {
    return await handleDownloadWebsite(prisma, request, (await params).id);
  } catch (error) {
    return errorResponse(error);
  }
}
